homePage:
    path: /
    controller: \App\Controller\PostController
    action: home

showOnePost:
    path: /article/{id}
    controller: \App\Controller\PostController
    action: show

listUsers:
    path: /users
    controller: \App\Controller\UserController
    action: users

showOneUser:
    path: /users/{id}
    controller: \App\Controller\UserController
    action: user

deleteOneUser:
    path: /article/delete/{id}
    controller: \App\Controller\PostController
    action: delete

# Auth routes:

login:
    path: /login
    controller: \App\Controller\UserController
    action: login

postLogin:
    path: /login
    controller: \App\Controller\UserController
    action: postLogin

register:
    path: /register
    controller: \App\Controller\UserController
    action: register

postRegister:
    path: /postRegister
    controller: \App\Controller\UserController
    action: postRegister