homePage:
    path: /
    controller: \App\Controller\PostController
    action: home

showOnePost:
    path: /article/{id}
    controller: \App\Controller\PostController
    action: show

showTest:
    path: /show
    controller: \App\Controller\PostController
    action: showTest

listUsers:
    path: /users
    controller: \App\Controller\UserController
    action: users

showOneUser:
    path: /users/{id}
    controller: \App\Controller\UserController
    action: user
