homePage:
    path: /
    controller: \App\Controller\PostController
    action: home

showOnePost:
    path: /article/{id}
    controller: \App\Controller\PostController
    action: show

listUsers:
    path: /users
    controller: \App\Controller\UserController
    action: users

showOneUser:
    path: /users/{id}
    controller: \App\Controller\UserController
    action: user


# Admin routes

listAdminPosts:
    path: dashboard/article
    controller: \App\Controller\PostController
    action: AdminPosts

deleteOnePost:
    path: /deletePost/{id}
    controller: \App\Controller\PostController
    action: delete